version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:10
    working_directory: ~/blog
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-node-10-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      # 빌드 결과를 워크스페이스에 유지
      - persist_to_workspace:
          root: ~/blog
          paths:
            - public
      - save_cache:
          key: dependency-cache-node-10-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - add_ssh_keys:
          fingerprints:
            - 'e3:80:b0:a8:8e:21:16:53:d5:db:1f:96:38:ef:b9:96'
      - run:
          name: Add host's key
          command: ssh-keyscan -t rsa $DEPLOY_HOST >> ~/.ssh/known_hosts
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install rsync
      - deploy:
          name: DEPLOY_HOST
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avh /tmp/workspace/public/* ubuntu@${DEPLOY_HOST}:/home/ubuntu/www/blog --delete
            else
              echo "Not master branch, dry run only"
            fi
